### ISSUE TITLE
[BUG] docker-composer: It's not possible to reutilize image built by another service

### ISSUE THREAD

**Issue by PicoleDeLimao** [SAP/InfraBox#238]
Let's say I have the following docker-compose file:
```
service1:
 build:
   context: .
   dockerfile: ./Dockerfile
 image: service1:latest
service2:
  build:
   context: ./service2/
   dockerfile: ./Dockerfile
  depends_on: ["service1"]
```

In this docker-compose, I'm building the service1 image and tagging it as "service1:latest". So logically I should be able to use it in the Dockerfile of service2, like this:

service2 dockerfile:
```
FROM service1:latest
```

I have tested locally and it works as expected, however, it does not work on Infrabox.

Why??

First: the image of "service1" is tagged with a weird prefix other than the tag I defined. Example:

ha-eu-de-1.infrabox.datahub.only.sap/project-id/my-job/service1

Second: When building the image of service2, I get the following error:

failed to build: pull access denied for service1, repository does not exist or may require 'docker login'
