### ISSUE TITLE
Simple RBAC for users

### ISSUE THREAD

**Issue by mwieczorek** [SAP/InfraBox#77]
**Is your feature request related to a problem? Please describe.**
I read docs and I guess it's not possible right now to give users different roles? F.e. I'd like to give 'read-only' access to every github user but write access only to users from specified orgs/teams

**Describe the solution you'd like**
Right now we can configure helm chart with:
```
github:
  login:
    allowed_organizations: org1
```

Id like to be able to use predefined roles here, like:
```
github:
  login:
    read-only: all #or some other predefined name, because 'all' is an existing org in github.com
    write:
      allowed_organizations: org1       
```

Also it would be good to be able to assign roles not only to whole org but also for team inside org, fe:
```
allowed_organizations: org1:team1
```
